{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ragbox.fullname" . }}
  labels:
    {{- include "ragbox.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ragbox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
